services:
  backend:
    image: brabodopedro/docs-todo:backend
    container_name: laravel_app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: brabodopedro/docs-todo:frontend
    container_name: react_front
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
