version: "3.8"

services:
  backend:
    build:
      context: ./Projeto-ToDo-back
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./Projeto-ToDo-back:/var/www
    depends_on:
      - db
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./Projeto-ToDo-front
    container_name: react_front
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
